services:
  diplomas_mid:
    container_name: diplomas-mid-local
    build:
      context: .
    environment:
      DIPLOMAS_MID_HTTP_PORT: ${DIPLOMAS_MID_HTTP_PORT}
      FIRMA_ELECTRONICA_MID_URL: ${FIRMA_ELECTRONICA_MID_URL}
      DIPLOMAS_CRUD_URL: ${DIPLOMAS_CRUD_URL}
      ADMINISTRATIVA_AMAZON_API_URL: ${ADMINISTRATIVA_AMAZON_API_URL}
      DOCUMENTOS_CRUD_GESTOR_DOCUMENTAL_URL: ${DOCUMENTOS_CRUD_GESTOR_DOCUMENTAL_URL}
      GESTOR_DOCUMENTAL_DOCUMENT_URL: ${GESTOR_DOCUMENTAL_DOCUMENT_URL}
      PAZ_Y_SALVOS_CRUD_URL: ${PAZ_Y_SALVOS_CRUD_URL}
      PAZ_Y_SALVOS_APROBADOS_QUERY: ${PAZ_Y_SALVOS_APROBADOS_QUERY}
      ACADEMICA_CORE_SERVICE_URL: ${ACADEMICA_CORE_SERVICE_URL}
      PARAMETROS_CRUD_URL: ${PARAMETROS_CRUD_URL}
      DIPLOMA_PREVIEW_QR_DEMO_URL: ${DIPLOMA_PREVIEW_QR_DEMO_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DIPLOMAS_S3_BUCKET: ${DIPLOMAS_S3_BUCKET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8090:8090"
