appname = diplomas_mid
httpport = ${DIPLOMAS_MID_HTTP_PORT}
runmode = ${DIPLOMAS_MID_RUNMODE}
autorender = false
copyrequestbody = true

FirmaElectronicaMidURL = ${FIRMA_ELECTRONICA_MID_URL}
DiplomasCrudURL = ${DIPLOMAS_CRUD_URL}
AdministrativaAmazonAPIURL = ${ADMINISTRATIVA_AMAZON_API_URL}
DocumentosCrudGestorDocumentalURL = ${DOCUMENTOS_CRUD_GESTOR_DOCUMENTAL_URL}
GestorDocumentalDocumentURL = ${GESTOR_DOCUMENTAL_DOCUMENT_URL}
PazYSalvosCrudURL = ${PAZ_Y_SALVOS_CRUD_URL}
PazYSalvosAprobadosQuery = ${PAZ_Y_SALVOS_APROBADOS_QUERY}
AcademicaCoreServiceURL = ${ACADEMICA_CORE_SERVICE_URL}
ParametrosCrudURL = ${PARAMETROS_CRUD_URL}
DiplomaPreviewQRDemoURL = ${DIPLOMA_PREVIEW_QR_DEMO_URL}
DiplomaInstitutionalLogoPath = ${DIPLOMA_INSTITUTIONAL_LOGO_PATH}
DiplomaCambriaFontPath = ${DIPLOMA_CAMBRIA_FONT_PATH}
DiplomaCambriaBoldFontPath = ${DIPLOMA_CAMBRIA_BOLD_FONT_PATH}
DiplomaEngraversFontPath = ${DIPLOMA_ENGRAVERS_FONT_PATH}

AWSRegion = ${AWS_REGION}
AWSEndpointURL = ${AWS_ENDPOINT_URL}
AWSAccessKeyID = ${AWS_ACCESS_KEY_ID}
AWSSecretAccessKey = ${AWS_SECRET_ACCESS_KEY}
DiplomasS3Bucket = ${DIPLOMAS_S3_BUCKET}
