appname = diplomas_mid
httpport = ${DIPLOMAS_MID_HTTP_PORT}
runmode = ${DIPLOMAS_MID_RUNMODE}
autorender = false
copyrequestbody = true

FirmaElectronicaMidURL = ${FIRMA_ELECTRONICA_MID_URL}
DiplomasCrudURL = ${DIPLOMAS_CRUD_URL}
AdministrativaAmazonAPIURL = ${ADMINISTRATIVA_AMAZON_API_URL}
DocumentosCrudGestorDocumentalURL = ${DOCUMENTOS_CRUD_GESTOR_DOCUMENTAL_URL}

AWSRegion = ${AWS_REGION}
AWSEndpointURL = ${AWS_ENDPOINT_URL}
AWSAccessKeyID = ${AWS_ACCESS_KEY_ID}
AWSSecretAccessKey = ${AWS_SECRET_ACCESS_KEY}
DiplomasS3Bucket = ${DIPLOMAS_S3_BUCKET}
